/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressLink: typeof import('./src/components/AddressLink.vue')['default']
    DataStructureView: typeof import('./src/components/DataStructureView.vue')['default']
    DSValue: typeof import('./src/components/DSValue.vue')['default']
    FieldTable: typeof import('./src/components/FieldTable.vue')['default']
    LinkedListChain: typeof import('./src/components/LinkedListChain.vue')['default']
    MemoryCell: typeof import('./src/components/MemoryCell.vue')['default']
    MemoryMap: typeof import('./src/components/MemoryMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgArrow: typeof import('./src/components/SvgArrow.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
